# Generated by Django 3.2.9 on 2022-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPIapp', '0002_auto_20220614_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Elsie', max_length=100),
        ),
    ]
